{{- if and .Values.persistence.enabled .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "onboarding.fullname" . }}-pvc
  labels:
    {{- include "onboarding.labels" . | nindent 4 }}
  annotations:
  {{- .Values.persistence.annotations }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}