server:
  port: 8080
  staticPath: ./static
  storage:
    destFolder: files
    maxSizeMB: 5
  cors:
    origin: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Content-Type
      - Authorization
      - X-Organization
    credentials: true
    optionsSuccessStatus: 204
    maxAge: 600
logging:
  level: info
database:
  type: postgres
  host: localhost
  port: 5432
  username: ''
  password: ''
  database: onboarding
  synchronize: true
  logging: false
app:
  login:
    openIdUrl: ''
    clientId: ''
    clientSecret: ''
    scope: openid
    codeChallenge: true
  keycloak:
    grantType: password
    clientId: 'admin-cli'
  tir: {}
email:
  enabled: false
  from: 'onboarding@seamware.com'
  update:
    subject: 'OnBoarding Portal - Registration updated'
    html: 'file://./templates/update.html'
  submit:
    subject: 'OnBoarding Portal - Registration submited'
    html: 'file://./templates/submit.html'
